// src/entities/SoloQuestState/index.ts
export type {
    RelationshipStatus,
    ProfileGender,
    UserInterestTag,
    UserProfileDetails,
    UpdateProfileDetailsRequest,
    SoloQuestStatus,
    DepositPolicy,
    TargetGender,
    SoloQuestDetails,
    CreateSoloQuestRequest,
    SoloQuestFeedParams,
    SoloQuestApplicationStatus,
    SoloQuestApplication,
    CreateApplicationRequest,
    ApplicationActionRequest,
    CheckInRequest,
    CheckInResponse,
    ReputationMarkType,
    ReputationSource,
    ReputationMark,
    UserReputation,
    AppealRequest,
} from './model/types';

export {
    soloQuestApi,
    useGetMyProfileDetailsQuery,
    useUpdateMyProfileDetailsMutation,
    useGetUserProfileDetailsQuery,
    useCreateSoloQuestMutation,
    useGetSoloQuestFeedQuery,
    useGetSoloQuestQuery,
    useGetMySoloQuestsQuery,
    useCancelSoloQuestMutation,
    useApplyToQuestMutation,
    useGetQuestApplicationsQuery,
    useGetMyApplicationsQuery,
    useAcceptApplicationMutation,
    useDeclineApplicationMutation,
    useSendCounterMessageMutation,
    useReplyToCounterMessageMutation,
    useWithdrawApplicationMutation,
    useCheckInMutation,
    useGetQuestWagerQuery,
    useDisputeQuestMutation,
    useGetUserReputationQuery,
    useAppealMarkMutation,
} from './model/slice/soloQuestApi';
