import { createStyles } from '../../shared/ui/theme';
import { Theme } from '../../shared/ui/theme/types';

export const styles = createStyles((theme: Theme) => ({
    container: {
        flex: 1,
        backgroundColor: theme.colors.background.primary,
    },
    loadingContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    loadingText: {
        marginTop: theme.spacing.md,
        fontSize: theme.typography.fontSize.base,
        color: theme.colors.text.secondary,
    },
    errorContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        padding: theme.spacing.xl,
    },
    errorText: {
        fontSize: theme.typography.fontSize.lg,
        color: theme.colors.text.secondary,
        marginTop: theme.spacing.md,
        marginBottom: theme.spacing.xl,
    },
    retryButton: {
        backgroundColor: theme.colors.primary.main,
        paddingHorizontal: theme.spacing.xl,
        paddingVertical: theme.spacing.sm,
        borderRadius: theme.layout.borderRadius.md,
    },
    retryButtonText: {
        color: theme.colors.text.inverse,
        fontSize: theme.typography.fontSize.base,
        fontWeight: theme.typography.fontWeight.semibold,
    },
    header: {
        backgroundColor: theme.colors.primary.main,
        padding: theme.spacing.lg,
        paddingTop: theme.spacing.md,
    },
    headerContent: {
        flex: 1,
    },
    deleteHeaderButton: {
        padding: theme.spacing.xs,
        marginLeft: theme.spacing.xs,
        backgroundColor: 'rgba(255, 59, 48, 0.8)',
        borderRadius: theme.layout.borderRadius.md,
    },
    title: {
        fontSize: theme.typography.fontSize['2xl'],
        fontWeight: theme.typography.fontWeight.bold,
        color: theme.colors.text.inverse,
        marginBottom: theme.spacing.sm,
    },
    badgeContainer: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: theme.spacing.xs,
    },
    typeBadge: {
        backgroundColor: 'rgba(255, 255, 255, 0.3)',
        paddingHorizontal: theme.spacing.sm,
        paddingVertical: theme.spacing.xs,
        borderRadius: theme.layout.borderRadius.lg,
    },
    statusBadge: {
        paddingHorizontal: theme.spacing.sm,
        paddingVertical: theme.spacing.xs,
        borderRadius: theme.layout.borderRadius.lg,
    },
    statusActive: {
        backgroundColor: 'rgba(76, 175, 80, 0.7)',
    },
    statusCompleted: {
        backgroundColor: 'rgba(33, 150, 243, 0.7)',
    },
    statusFailed: {
        backgroundColor: 'rgba(244, 67, 54, 0.7)',
    },
    badgeText: {
        color: theme.colors.text.inverse,
        fontSize: theme.typography.fontSize.xs,
        fontWeight: theme.typography.fontWeight.semibold,
    },
    content: {
        padding: theme.spacing.md,
    },
    descriptionContainer: {
        backgroundColor: theme.colors.background.primary,
        borderRadius: theme.layout.borderRadius.md,
        padding: theme.spacing.md,
        marginBottom: theme.spacing.md,
        elevation: 1,
        shadowOpacity: 0.1,
        shadowRadius: 2,
        shadowOffset: { width: 0, height: 1 },
    },
    descriptionTitle: {
        fontSize: theme.typography.fontSize.base,
        fontWeight: theme.typography.fontWeight.bold,
        marginBottom: theme.spacing.xs,
        color: theme.colors.text.primary,
    },
    descriptionText: {
        fontSize: theme.typography.fontSize.sm,
        color: theme.colors.text.secondary,
        lineHeight: 20,
    },
    debugContainer: {
        backgroundColor: '#ffe6e6',
        borderRadius: theme.layout.borderRadius.md,
        padding: theme.spacing.md,
        marginBottom: theme.spacing.md,
        borderWidth: 1,
        borderColor: '#ffcccc',
    },
    debugTitle: {
        fontSize: theme.typography.fontSize.sm,
        fontWeight: theme.typography.fontWeight.bold,
        color: '#cc0000',
        marginBottom: theme.spacing.xs,
    },
    debugText: {
        fontSize: theme.typography.fontSize.xs,
        color: theme.colors.text.secondary,
        marginBottom: 4,
    },
    section: {
        backgroundColor: theme.colors.background.primary,
        borderRadius: theme.layout.borderRadius.md,
        padding: theme.spacing.md,
        marginBottom: theme.spacing.md,
        elevation: 1,
        shadowOpacity: 0.1,
        shadowRadius: 2,
        shadowOffset: { width: 0, height: 1 },
    },
    sectionTitle: {
        fontSize: theme.typography.fontSize.lg,
        fontWeight: theme.typography.fontWeight.semibold,
        marginBottom: theme.spacing.sm,
        color: theme.colors.text.primary,
    },
    infoRow: {
        flexDirection: 'row',
        marginBottom: theme.spacing.xs,
        alignItems: 'center',
    },
    infoLabel: {
        width: 100,
        fontSize: theme.typography.fontSize.sm,
        color: theme.colors.text.secondary,
        fontWeight: theme.typography.fontWeight.medium,
    },
    infoValue: {
        flex: 1,
        fontSize: theme.typography.fontSize.sm,
        color: theme.colors.text.primary,
    },
    verificationMethods: {
        flex: 1,
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 6,
    },
    verificationBadge: {
        backgroundColor: '#E3F2FD',
        paddingHorizontal: theme.spacing.sm,
        paddingVertical: 4,
        borderRadius: theme.layout.borderRadius.lg,
    },
    verificationText: {
        fontSize: theme.typography.fontSize.xs,
        color: '#1976D2',
        fontWeight: theme.typography.fontWeight.medium,
    },
    creatorSection: {
        backgroundColor: theme.colors.background.primary,
        borderRadius: theme.layout.borderRadius.md,
        padding: theme.spacing.md,
        marginBottom: theme.spacing.md,
        elevation: 1,
        shadowOpacity: 0.1,
        shadowRadius: 2,
        shadowOffset: { width: 0, height: 1 },
    },
    creatorInfo: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    creatorName: {
        fontSize: theme.typography.fontSize.base,
        color: theme.colors.primary.main,
        fontWeight: theme.typography.fontWeight.medium,
    },
    quizContainer: {
        backgroundColor: theme.colors.background.primary,
        borderRadius: theme.layout.borderRadius.md,
        padding: theme.spacing.md,
        marginBottom: theme.spacing.md,
        elevation: 1,
        shadowOpacity: 0.1,
        shadowRadius: 2,
        shadowOffset: { width: 0, height: 1 },
    },
    quizTitle: {
        fontSize: theme.typography.fontSize.lg,
        fontWeight: theme.typography.fontWeight.semibold,
        marginBottom: theme.spacing.sm,
        color: theme.colors.text.primary,
    },
    quizDetails: {
        marginTop: theme.spacing.xs,
    },
    quizRow: {
        flexDirection: 'row',
        marginBottom: theme.spacing.xs,
    },
    quizLabel: {
        width: 120,
        fontSize: theme.typography.fontSize.sm,
        color: theme.colors.text.secondary,
        fontWeight: theme.typography.fontWeight.medium,
    },
    quizValue: {
        flex: 1,
        fontSize: theme.typography.fontSize.sm,
        color: theme.colors.text.primary,
    },
    actionSection: {
        gap: theme.spacing.md,
    },
    button: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        padding: theme.spacing.md,
        borderRadius: theme.layout.borderRadius.md,
        gap: theme.spacing.sm,
        elevation: 2,
        shadowOpacity: 0.2,
        shadowRadius: 4,
        shadowOffset: { width: 0, height: 2 },
    },
    buttonDisabled: {
        opacity: 0.7,
        backgroundColor: '#A0A0A0',
    },
    primaryButton: {
        backgroundColor: theme.colors.primary.main,
    },
    secondaryButton: {
        backgroundColor: theme.colors.warning.main,
    },
    successButton: {
        backgroundColor: theme.colors.success.main,
    },
    buttonText: {
        color: theme.colors.text.inverse,
        fontSize: theme.typography.fontSize.base,
        fontWeight: theme.typography.fontWeight.semibold,
    },
    audioContainer: {
        backgroundColor: theme.colors.background.primary,
        borderRadius: theme.layout.borderRadius.md,
        padding: theme.spacing.md,
        marginBottom: theme.spacing.md,
        elevation: 1,
        shadowOpacity: 0.1,
        shadowRadius: 2,
        shadowOffset: { width: 0, height: 1 },
    },
    audioRequirement: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#fff3e0',
        padding: theme.spacing.md,
        borderRadius: theme.layout.borderRadius.md,
        marginTop: theme.spacing.md,
        gap: theme.spacing.sm,
    },
    audioRequirementText: {
        flex: 1,
        fontSize: theme.typography.fontSize.sm,
        color: theme.colors.text.secondary,
        fontWeight: theme.typography.fontWeight.medium,
    },
    cancelledBanner: {
        backgroundColor: theme.colors.error.main,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        padding: theme.spacing.md,
        gap: theme.spacing.sm,
    },
    cancelledBannerText: {
        color: theme.colors.text.inverse,
        fontWeight: theme.typography.fontWeight.bold,
        fontSize: theme.typography.fontSize.base,
    },
}));
