import { createStyles } from '../../shared/ui/theme/createStyles';

export const themeStyles = createStyles(theme => ({
  container: {
    flex: 1,
    backgroundColor: theme.colors.background.secondary || '#f5f5f5',
  },
  scrollContent: {
    flexGrow: 1,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
    backgroundColor: theme.colors.background.primary || 'white',
  },
  loadingText: {
    marginTop: 12,
    fontSize: 16,
    color: theme.colors.text.secondary || '#555',
  },
  errorContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
    backgroundColor: theme.colors.background.primary || 'white',
  },
  errorText: {
    marginTop: 12,
    fontSize: 16,
    color: theme.colors.text.secondary || '#555',
    marginBottom: 20,
    textAlign: 'center',
  },
  retryButton: {
    backgroundColor: theme.colors.primary.main || '#4CAF50',
    paddingVertical: 10,
    paddingHorizontal: 24,
    borderRadius: 8,
  },
  retryButtonText: {
    color: theme.colors.text.inverse || 'white',
    fontWeight: 'bold',
  },
  header: {
    padding: 24,
    backgroundColor: theme.colors.primary.main || '#4CAF50',
    alignItems: 'center',
  },
  title: {
    fontSize: 22,
    fontWeight: 'bold',
    color: theme.colors.text.inverse || 'white',
    textAlign: 'center',
  },
  subtitle: {
    fontSize: 16,
    color: 'rgba(255, 255, 255, 0.9)',
    marginTop: 6,
  },
  content: {
    padding: 16,
  },
  descriptionContainer: {
    backgroundColor: theme.colors.background.primary || 'white',
    borderRadius: 12,
    padding: 16,
    marginBottom: 20,
    elevation: 2,
    shadowOpacity: 0.1,
    shadowRadius: 3,
    shadowOffset: { width: 0, height: 1 },
  },
  descriptionTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 8,
    color: theme.colors.text.primary || '#333',
  },
  descriptionText: {
    fontSize: 14,
    color: theme.colors.text.secondary || '#555',
    lineHeight: 20,
  },
  methodsContainer: {
    marginBottom: 20,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 16,
    color: theme.colors.text.primary || '#333',
    paddingLeft: 4,
  },
  submitButton: {
    backgroundColor: theme.colors.primary.main || '#4CAF50',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 16,
    borderRadius: 12,
    marginTop: 10,
    marginBottom: 30,
    elevation: 2,
    shadowOpacity: 0.1,
    shadowRadius: 3,
    shadowOffset: { width: 0, height: 2 },
  },
  submitButtonText: {
    color: theme.colors.text.inverse || 'white',
    fontWeight: 'bold',
    fontSize: 16,
    marginLeft: 8,
  },
  disabledButton: {
    backgroundColor: theme.colors.primary.light || '#A5D6A7',
    opacity: 0.8,
  },
  processingOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: theme.colors.background.overlay || 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1000,
  },
  processingText: {
    color: theme.colors.text.inverse || 'white',
    marginTop: 16,
    fontSize: 16,
    fontWeight: 'bold',
  },
  noMethodsText: {
    fontSize: 14,
    color: theme.colors.text.disabled || '#757575',
    fontStyle: 'italic',
    textAlign: 'center',
    padding: 30,
    backgroundColor: theme.colors.background.primary || 'white',
    borderRadius: 12,
  },
}));
